version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-fastify
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
    command: sh -c "npm install && npm run dev"
