name: Persona
services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install;npm run dev"
    ports:
      - 3000
    volumes:
      - ./backend:/backend
    environment:
      - PG_DATABASE=${DB_DATABASE}
      - PG_USER=${DB_USERNAME}
      - PG_PASSWORD=${DB_PASSWORD}
      - PG_HOST=database

  frontend:
    image: nginx:alpine
    ports:
      - 80
    volumes:
      - ./frontend:/usr/share/nginx/html

  database:
    image: db
    container_name: database
    build: ./database
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=personas
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - backend
      - frontend
  proxy:
    image: proxy
    container_name: proxy
    ports: -80:80 -443:443
    volumes: -./certs:/etc/nginx/certs
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on: -frontend -backend
