name: Persona
services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install;npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
    environment:
      - PGDATABASE=${DB_DATABASE}
      - PGUSER=${DB_USERNAME}
      - PGPASSWORD=${DB_PASSWORD}
      - PGHOST=database
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

  database:
    image: db
    container_name: database
    build: ./database
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=personas
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
  proxy:
    image: nginx:alpine
    container_name: proxy
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./proxy/certs:/etc/nginx/certs
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

    depends_on:
      - backend
      - frontend
