version: '27.2.0'

services:
  backend:
    image: backend:latest
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install;npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
