services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/data.json:/usr/src/app/src/data.json

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
